using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Api.Migrations
{
    /// <inheritdoc />
    public partial class populateSubject : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"INSERT INTO SUBJECT (id, name) values(UUID(), 'Língua Portuguesa e Literatura'),
            (UUID(), 'Inglês'),
            (UUID(), 'Espanhol'),
            (UUID(), 'Arte'),
            (UUID(), 'Educação Física'),
            (UUID(), 'Geografia'),
            (UUID(), 'História'),
            (UUID(), 'Filosofia'),
            (UUID(), 'Sociologia'),
            (UUID(), 'Matemática'),
            (UUID(), 'Física'),
            (UUID(), 'Química'),
            (UUID(), 'Biologia'),
            (UUID(), 'Informática'),
            (UUID(), 'Gestão Organizacional e Empreendedorismo'),
            (UUID(), 'Produção de texto Técnico-Científico I'),
            (UUID(), 'Produção de texto Técnico-Científico II'),
            (UUID(), 'Introdução a Química dos Alimentos'),
            (UUID(), 'Biologia aplicada a Alimentos'),
            (UUID(), 'Termologia Aplicada a Tecnologia de Alimentos'),
            (UUID(), 'Segurança do Trabalho'),
            (UUID(), 'Gestão Ambiental'),
            (UUID(), 'Introdução a Tecnologia de Alimentos'),
            (UUID(), 'Técnicas de Laboratório de Alimentos'),
            (UUID(), 'Química e Bioquímica dos Alimentos: componentes principais'),
            (UUID(), 'Química e Bioquímica dos Alimentos: componentes secundários e transformações'),
            (UUID(), 'Química e Bioquímica dos Alimentos: experimental'),
            (UUID(), 'Microbiologia dos Alimentos'),
            (UUID(), 'Biotecnologia Aplicada aos Alimentos'),
            (UUID(), 'Controle Estatístico da Qualidade'),
            (UUID(), 'Tecnologia de Frutas e Hortaliças'),
            (UUID(), 'Tecnologia de Cereais'),
            (UUID(), 'Tecnologia de Mel'),
            (UUID(), 'Higiene e Segurança Alimentar'),
            (UUID(), 'Máquinas, Equipamentos, Processos e Operações Unitárias'),
            (UUID(), 'Análise dos Alimentos'),
            (UUID(), 'Tecnologia de Leite e Derivados'),
            (UUID(), 'Tecnologia de Carnes e Pescados'),
            (UUID(), 'Embalagem, Rotulagem e Logística'),
            (UUID(), 'Análise Sensorial'),
            (UUID(), 'Filosofia, Ciência e Tecnologia'),
            (UUID(), 'Sociologia do Trabalho'),
            (UUID(), 'Qualidade de Vida e Trabalho'),
            (UUID(), 'Gestão e Empreendedorismo'),
            (UUID(), 'Instalação e Montagem de Computadores'),
            (UUID(), 'Práticas de Eletricidade'),
            (UUID(), 'Operação e Organização de Computadores'),
            (UUID(), 'Eletrônica Analógica'),
            (UUID(), 'Eletrônica Digital'),
            (UUID(), 'Eletrônica de Potência'),
            (UUID(), 'Manutenção Básica de Computadores'),
            (UUID(), 'Manutenção de Fontes de Alimentação'),
            (UUID(), 'Manutenção de Periféricos'),
            (UUID(), 'Manutenção Avançada de Computadores'),
            (UUID(), 'Infraestrutura de Redes de Computadores'),
            (UUID(), 'Sistemas Operacionais de Redes de Computadores'),
            (UUID(), 'Gestão de Serviços em Informática'),
            (UUID(), 'Gestão Organizacional'),
            (UUID(), 'Fundamentos de Lógica e Algoritmos'),
            (UUID(), 'Eletricidade Instrumental'),
            (UUID(), 'Eletrônica Analógica e Digital'),
            (UUID(), 'Organização e Manutenção de Computadores'),
            (UUID(), 'Programação Estruturada e Orientada a Objetos'),
            (UUID(), 'Programação com Acesso a Banco de Dados'),
            (UUID(), 'Projeto de Desenvolvimento de Software'),
            (UUID(), 'Autoria Web'),
            (UUID(), 'Programação para Internet'),
            (UUID(), 'Arquitetura de redes de computadores e Tecnologia de implementação de redes'),
            (UUID(), 'Fundamentos de sistemas operacionais e Sistemas operacionais de redes'),
            (UUID(), 'Língua Portuguesa'),
            (UUID(), 'Leitura e Escrita de Textos Acadêmicos e de Divulgação Científica'),
            (UUID(), 'Matemática Básica'),
            (UUID(), 'Psicologia da Aprendizagem'),
            (UUID(), 'Didática'),
            (UUID(), 'Organização e Gestão da Educação Brasileira'),
            (UUID(), 'Mídias Educacionais'),
            (UUID(), 'Educação Inclusiva'),
            (UUID(), 'LIBRAS'),
            (UUID(), 'Fundamentos da Educação I'),
            (UUID(), 'Fundamentos da Educação II'),
            (UUID(), 'Epistemologia da Ciência'),
            (UUID(), 'Metodologia do Trabalho Científico'),
            (UUID(), 'Metodologia do Ensino de Química I'),
            (UUID(), 'Metodologia do Ensino de Química II'),
            (UUID(), 'Química Geral I'),
            (UUID(), 'Química Geral II'),
            (UUID(), 'Química Experimental I'),
            (UUID(), 'Química Experimental II'),
            (UUID(), 'Química Inorgânica'),
            (UUID(), 'Química Inorgânica de Coordenação'),
            (UUID(), 'Físico-Química Teórica e Experimental I'),
            (UUID(), 'Físico-Química Teórica e Experimental II'),
            (UUID(), 'Físico Química Teórica e Experimental III'),
            (UUID(), 'Química Orgânica Fundamental'),
            (UUID(), 'Mecanismo de Reações Orgânicas'),
            (UUID(), 'Química Analítica Qualitativa'),
            (UUID(), 'Química Analítica Quantitativa'),
            (UUID(), 'Química dos Elementos'),
            (UUID(), 'Química Inorgânica Experimental'),
            (UUID(), 'Cálculo Diferencial e Integral I'),
            (UUID(), 'Cálculo Diferencial e Integral II'),
            (UUID(), 'Física I'),
            (UUID(), 'Física II'),
            (UUID(), 'Bioquímica'),
            (UUID(), 'Fundamentos da Pesquisa em Educação Química'),
            (UUID(), 'Biologia para o Ensino de Ciências'),
            (UUID(), 'Química Orgânica Experimental'),
            (UUID(), 'Química Ambiental'),
            (UUID(), 'Estatística aplicada à Química'),
            (UUID(), 'Concepções e Práticas da Educação de Jovens e Adultos'),
            (UUID(), 'Concepções e Práticas de Avaliação da Aprendizagem'),
            (UUID(), 'Educação para a Diversidade'),
            (UUID(), 'Educação para o Desenvolvimento Sustentável'),
            (UUID(), 'Ética da Docência'),
            (UUID(), 'Fundamentos da Educação Profissional e Tecnológica'),
            (UUID(), 'Filosofia da Técnica e da Tecnologia'),
            (UUID(), 'Formação de Professores e Trabalho Docente'),
            (UUID(), 'Fundamentos da Educação a Distância'),
            (UUID(), 'LIBRAS II'),
            (UUID(), 'Teoria e Organização curricular'),
            (UUID(), 'Educação em Direitos Humanos'),
            (UUID(), 'Análises de Águas e Efluentes I'),
            (UUID(), 'Análises de Águas e Efluentes II'),
            (UUID(), 'Espectroscopia dos Compostos de Coordenação'),
            (UUID(), 'Fundamentos da Espectroscopia de Absorção Molecular no UV/Vis'),
            (UUID(), 'Métodos Cromatográficos'),
            (UUID(), 'Métodos Instrumentais de Caracterização de Compostos Orgânicos'),
            (UUID(), 'Mineralogia'),
            (UUID(), 'Química dos Biocombustíveis'),
            (UUID(), 'Química de Produtos Naturais'),
            (UUID(), 'Tratamento de Água e Efluentes'),
            (UUID(), 'Física para o Ensino de Ciências'),
            (UUID(), 'Língua Inglesa'),
            (UUID(), 'Informática Básica'),
            (UUID(), 'Cálculo Diferencial e Integral'),
            (UUID(), 'Estatística'),
            (UUID(), 'Ética e Cidadania'),
            (UUID(), 'Química Geral'),
            (UUID(), 'Química Orgânica'),
            (UUID(), 'Físico-Química'),
            (UUID(), 'Química Analítica'),
            (UUID(), 'Desenho Técnico Auxiliado por Computador'),
            (UUID(), 'Microbiologia de Alimentos I'),
            (UUID(), 'Microbiologia de Alimentos II'),
            (UUID(), 'Princípios da Conservação de Alimentos'),
            (UUID(), 'Química dos Alimentos'),
            (UUID(), 'Matérias-Primas Agropecuárias'),
            (UUID(), 'Gestão da Qualidade e Legislação de Alimentos'),
            (UUID(), 'Bioquímica dos Alimentos'),
            (UUID(), 'Termodinâmica Aplicada e Fenômenos de Transportes'),
            (UUID(), 'Tecnologia de Laticínios'),
            (UUID(), 'Biotecnologia de Alimentos'),
            (UUID(), 'Tecnologia de Pescado'),
            (UUID(), 'Tecnologia de Carnes'),
            (UUID(), 'Armazenamento e Logística'),
            (UUID(), 'Operações Unitárias Aplicadas à Alimentos'),
            (UUID(), 'Higiene da Indústria de Alimentos'),
            (UUID(), 'Instrumentação e Instalações Industriais'),
            (UUID(), 'Embalagens'),
            (UUID(), 'Língua Espanhola'),
            (UUID(), 'Análise de Água'),
            (UUID(), 'Tratamento de Águas e Efluentes na Indústria Alimentícia'),
            (UUID(), 'Tecnologia de Bebidas Alcóolicas'),
            (UUID(), 'Tecnologia de Óleos e Gorduras'),
            (UUID(), 'Tecnologia de Amido, Farinhas e Derivados'),
            (UUID(), 'Pesquisa e Desenvolvimento de Novos Produtos'),
            (UUID(), 'Tecnologia Pós-Colheita de Frutas e Hortaliças'),
            (UUID(), 'Sociologia e Tecnologia'),
            (UUID(), 'Empreendedorismo'),
            (UUID(), 'Introdução à Lógica e Programação'),
            (UUID(), 'Fundamentos de Sistemas Operacionais'),
            (UUID(), 'Padrões Web'),
            (UUID(), 'Sistemas Operacionais Abertos'),
            (UUID(), 'Bancos de Dados'),
            (UUID(), 'Programação Orientada a Objetos'),
            (UUID(), 'Desenvolvimento Web Front-end'),
            (UUID(), 'Redes de Computadores'),
            (UUID(), 'Estruturas de Dados'),
            (UUID(), 'Programação em Bancos de Dados'),
            (UUID(), 'Análise e Projeto de Sistemas Web'),
            (UUID(), 'Desenvolvimento Web Back-end'),
            (UUID(), 'Sistemas Digitais'),
            (UUID(), 'Desenvolvimento de Sistemas Corporativos'),
            (UUID(), 'Processo de Desenvolvimento e Implantação de Sistemas Web'),
            (UUID(), 'Sistemas Distribuídos'),
            (UUID(), 'Teste de Software'),
            (UUID(), 'Programação para Internet das Coisas'),
            (UUID(), 'Gerência e Conf. de Serviços para a Internet'),
            (UUID(), 'Desenvolvimento para Dispositivos Móveis'),
            (UUID(), 'Técnicas de Análise de Dados'),
            (UUID(), 'Segurança e Preservação de Dados'),
            (UUID(), 'Desenvolvimento Web para a Nuvem'),
            (UUID(), 'Introdução à Informática'),
            (UUID(), 'Educação Ambiental'),
            (UUID(), 'Psicologia das Relações de Trabalho'),
            (UUID(), 'Legislação Aplicada à Tecnologia da Informação'),
            (UUID(), 'Web Design'),
            (UUID(), 'Redes Multimídia'),
            (UUID(), 'Sistemas Operacionais Proprietários'),
            (UUID(), 'Tecnologias de Banco de Dados'),
            (UUID(), 'Desenvolvimento com Ferramentas RAD'),
            (UUID(), 'Sistemas Embarcados'),
            (UUID(), 'Governança de TI'),
            (UUID(), 'Qualidade de Software'),
            (UUID(), 'Gerenciamento de Projeto de Software'),
            (UUID(), 'Gestão de Pessoas'),
            (UUID(), 'Computação Forense'),
            (UUID(), 'Tópicos Avançados em Sistemas para Internet')", true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DELETE * FROM SUBJECT");
        }
    }
}
